version: '2'

services:

 openvpn-server:
    image: "kylemanna/openvpn"
    container_name: openvpn-server
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn:/etc/openvpn
    restart: always
    networks:
      mynet:
        aliases:
          - openvpn-server
networks:
  mynet:
    external:
     name: mynet
